### PR TITLE
Pull fixes on transferring container and resources in DigLocal

### PR DESCRIPTION
**Pull request by mokun**

### CODE REVIEW

**Comment by mokun** [comment]
@bevans2000 

How do I bypass the change in `CHANGELOG_3.6.2.md` ?

Somehow it can't be resolved automatically. 

It's just a simple thing. The `Master` Branch has `CHANGELOG_3.7.0.md` while the `3.6.X` branch has  `CHANGELOG_3.6.2.md`.

**Comment by bevans2000** [comment]
OK, I can see what you've done. The same editor has been made in both versions and I guess that is the cause. I can change the version on the master branch to close the gap. 
However I've got to say these change look quite large.

**Comment by mokun** [comment]
> However I've got to say these change look quite large.

Yes I'd say they are still bugfixes

**Comment by mokun** [comment]
We may as well change that filename in both branch to just `CHANGELOG.md`.

**Comment by bevans2000** [comment]
No, let's focus on just doing the minimal required until we get off the bugfix branch.

**Comment by bevans2000** [comment]
It's done. I merge the branch on the command line.

**Comment by mokun** [comment]
That's great. Thanks !

**Pull request merged**
