### PR TITLE
Edit MissionManager to resolve issue

### PR DESCRIPTION
**Pull request by muybien3433**
I believe that when CacheCreator was initialized as null  getRandomSelection method  couldn't satisfy condition 
"if (createdTime != null)" because createdTime was also null so it returned lastEntity(with is null) when (randomDouble <= probWeight) condition was true.

Assuming I created MarsTime instance right it should work. Due to #1438

### CODE REVIEW

**Comment by bevans2000** [comment]
Sounds a reasonable assumption. You can't really create a MarsTime instance. We get them off the Master clock.

**Comment by bevans2000** [comment]
Is this ready to merge to fix the problem?

**Comment by mokun** [comment]
Right ! Besides the null MarsTime, I can see a typo mistake. 

In the old MissionManager,
> private transient CacheCreator<MissionRating> missionProbCache = null;

In the old getNewMission(),
> List<MissionRating> missionProbCache = new ArrayList<>();

Both are called missionProbCache.

**Comment by muybien3433** [comment]
If you think 'MarsTime marsTime = Simulation.instance().getMasterClock().getMarsTime();' is right way to fetch, then it's ready to merge.

**Comment by mokun** [comment]
> If you think 'MarsTime marsTime = Simulation.instance().getMasterClock().getMarsTime();' is right way to fetch, then it's ready to merge.

@bevans2000 

Would you prefer to bring in a static MasterClock instance here in MissionManager ?

But in doing so, it would mean that we must override this MasterClock instance with a new one when deserializing or loading from a saved sim and it's really a hassle with having to keep track of so many of these static instances already.

**Comment by bevans2000** [comment]
Leave it as it is for now and we can sort this out later

**Pull request merged**
