### PR TITLE
Reporting Authority is configured in external XML

### PR DESCRIPTION
**Pull request by bevans2000**
Introduction of the governance.xml controls the specifics of the ReportingAuthority and associated MissionsAgendas.
The people.xml file has been reworked to align to selection names by country instead of a single list.

#363

### CODE REVIEW

**Comment by mokun** [comment]
I can definitely see the benefit of having a leaner and cleaner people.xml as follows : 

```
	<country-list>
		<country name="China">
			<first-name-list>
				<!-- Derived from https://en.wiki2.org/wiki/List_of_Chinese_astronauts 
					http://www.20000-names.com/male_chinese_names.htm -->
				<first-name value="Boming" gender="male" />
				<first-name value="Chongfu" gender="male" />
				<first-name value="Dazhe" gender="male" />
```

**Review by mokun — COMMENTED** [review]
Thanks ! Using the power of xml such as `governance.xml` to generate countries and sponsors is super awesome.

So, say, I want to add Brazil as a new country and its [Brazilian Space Agency](https://en.wikipedia.org/wiki/Brazilian_Space_Agency
) 

It's Agência Espacial Brasileira (AEB) in Portuguese.

Anything I need to be careful about that ?

**Comment by bevans2000** [comment]
> Thanks ! Using the power of xml such as `governance.xml` to generate countries and sponsors is super awesome.
> 
> So, say, I want to add Brazil as a new country and its [Brazilian Space Agency](https://en.wikipedia.org/wiki/Brazilian_Space_Agency)
> 
> It's Agência Espacial Brasileira (AEB) in Portuguese.
> 
> Anything I need to be careful about that ?

So I still need to make one more commit to make it easy to remove the ReportingAuthorityType enum. Once that is gone it will be totally driven  by what is in the XML file. This last change is quite easy but spread around various classes.

**Comment by bevans2000** [comment]
> I can definitely see the benefit of having a leaner and cleaner people.xml as follows :
> 
> ```
> 	<country-list>
> 		<country name="China">
> 			<first-name-list>
> 				
> 				<first-name value="Boming" gender="male" />
> 				<first-name value="Chongfu" gender="male" />
> 				<first-name value="Dazhe" gender="male" />
> ```

It is a lot easier to read.

**Pull request merged**
