### PR TITLE
Rework Settlement Map layers

### PR DESCRIPTION
**Pull request by bevans2000**
This aims to rework the map layers in the settlement to clean up the code and make it optimal. The map displays the "items" and then the LabelMapLayer cycle back over the units to render the labels. This means a double scan of all the itmes being displayed. The aim is to display labels as part of the item rendering.

Changes:
- Create ColorChoice which holds a 2 colour pairing used for rendering text and highlights. Removes the need of r2 variables being passed.
- AbstractMapLayer is new and provides reusable label drawing methods including multi-line for long labels.
- Font and ColorChoice is used as parameters for label drawing
- New WorkerMapLayer renders Worker objects according to user selection. Has a callback for ColorChoice to use.
- Selected Worker is always shown with labels.
- PersonMapLayer & RobotMapLayer use WorkerMapLayer to greatly simplify their implementation
- "unit" layers now draw labels as part of the main layer drawing instead of a seperate layer
- Correct problem with labels being auto-enabled when a Robot/Person is selected. Now respects users choice.
- StructureMapLayer & VehicleMapLayer use LocalBoundingObject for placement instead of 6 seperate parameters.
- Numerous code smells corrections
- Delete LabelMapLayer

Helps to support future change for #1166

### CODE REVIEW

**Comment by mokun** [comment]
>  the colours are not ideal for Vehicles

True

Also, how do we solve a person's label got overlapped by another ?

Currently it's very difficult to read a person/robot's label when another person/robot is nearby.

How do we cleanly separate one form another ?

Shall we make a label non-transparent ?

This way, they will be on top of one another. Only the selected one becomes  on top and is cleanly viewable.

**Comment by bevans2000** [comment]
Don't know about the overlapping labels but after this change it is clear to see what is going on.

**Comment by bevans2000** [comment]
Also, I now realise I should have split the StructureMapLayer into 2 separate classes, one for Building and the other for Construction. I will take care of it when I add Activity Spots to the Buildings display

**Comment by mokun** [comment]
> Don't know about the overlapping labels

You can see two persons labels almost 'merged together' when the two are next to each other.

When that's the case, it's very hard to read.

**Comment by bevans2000** [comment]
To be honest I see this as an annoyance more than than bug. Tracking the labels and having am avoidance algorithm.would be a lot of work for not enough benefit.

**Comment by mokun** [comment]
> Tracking the labels... would be a lot of work for not enough benefit.

Just added a white background box with raised edge to increase the contrast and single out the selected person/robot's status info.

**Pull request merged**
