### PR TITLE
Add missing messages to messages.properties

### PR DESCRIPTION
**Pull request by muybien3433**
Let me know if you find else missing messages.

### CODE REVIEW

**Comment by mokun** [comment]
Thanks for adding them back.

We have a few more. 

@bevans2000 @muybien3433 
Let's see if we devise a mechanism to automatically track which msg are invalid or missing. 
May be through a unit test ? ! 

It's such a huge list and we don't have to manually track down whatever is missing.

image

**Comment by mokun** [comment]
Also some RatingScore.x are gone.

```
01-Adir-01:414.550 (Warning) Msg : !!OngoingStudyListPanel.title??
01-Adir-01:414.550 (Warning) Msg : !!OngoingStudyListPanel.column.study??
01-Adir-01:414.550 (Warning) Msg : !!OngoingStudyListPanel.column.phase??
01-Adir-01:414.550 (Warning) Msg : !!OngoingStudyListPanel.column.researcher??
01-Adir-01:414.550 (Warning) Msg : !!OngoingStudyListPanel.column.settlement??
01-Adir-01:414.550 (Warning) Msg : !!FinishedStudyListPanel.title??
01-Adir-01:414.550 (Warning) Msg : !!FinishedStudyListPanel.column.study??
01-Adir-01:414.550 (Warning) Msg : !!FinishedStudyListPanel.column.phase??
01-Adir-01:414.550 (Warning) Msg : !!FinishedStudyListPanel.column.researcher??
01-Adir-01:414.550 (Warning) Msg : !!FinishedStudyListPanel.column.settlement??
01-Adir-01:414.550 (Warning) Msg : !!RatingScore.fitness??
01-Adir-01:414.550 (Warning) Msg : !!RatingScore.effort??
01-Adir-01:414.550 (Warning) Msg : !!RatingScore.favourite??
01-Adir-01:414.550 (Warning) Msg : !!RatingScore.capacity??
01-Adir-01:414.550 (Warning) Msg : !!RatingScore.shift??
```

**Comment by bevans2000** [comment]
Yes we could do it via a Unit test but we would need to add the checks to the specific unit tests. Can't have a single one because it would become too complex.
The problem is some of the msg keys are calculated on the fly and that is why the search missed them. 
A lot of enums use the auto generated key approach

**Comment by mokun** [comment]
Relates to https://github.com/mars-sim/mars-sim/issues/1071.

**Pull request merged**
