### PR TITLE
Show multiple Settlements in the Monitor Window

### LINKED ISSUE #903: Put settlements/stations/outposts of same space agency under one belt
**Is your feature request related to a problem? Please describe.**
- Both Europa and Arcadia are ESA settlement in scenario_default.xml. It would be silly to separate them into different settlement panel in Monitor Tool.

**Describe the solution you desire to see**
- List both Europa and Arcadia under one belt.

**Describe the rationale**
- if a settlement creates numerous weather/communication stations, mining stations, trading outposts, etc. it's more intuitive to find and see the general statistics of them in single location.
- In future, we may even create a dashboard showcasing combined statistics of related settlements/stations/outposts.

**Specifications  (please complete the following information):**
 - pre 3.6.0 build 8131

**Additional context**
- One unintentional effect was found in that two unrelated settlements were put under one panel in #900. We want it to happen under a different circumstance/reason.

### PR DESCRIPTION
**Pull request by bevans2000**
This PR consists of changes to allow Reporting Authorities to be used in the Monitor window filter selection. The activity consists of a number of high level changes:
- Adding Authorities to the MonitorWindow combo with an indication of the number of owned Settlements. 
- When an Authority is selected; the Settlement names are shown in the toolbar of the window.
- MonitorModel converted so the selection filter is a Set of Settlements instead of a singe one
- Adding a Settlement column to most tables that is automatically shown/hidden depending on the number of Settlement being filtered.
- Category model, i.e. Food & Goods, now shown one entry per Category per Settlement

close #903

### CODE REVIEW

**Comment by mokun** [comment]
Sounds good !

I'll release v3.7.0 by the end of this hour. 

Will check it out.

**Comment by mokun** [comment]
Now that we have a new branch 3.7.x, feel free to finish the pull !

**Comment by mokun** [comment]
It works well !

**Comment by bevans2000** [comment]
Yes I like it. You need a scenario with multiple Settlement on one Authority to see it best

**Comment by mokun** [comment]
Ready to create weather stations, communicator stations, etc. ?

**Comment by mokun** [comment]
>  I don't want to create another top-level Unit but would like to rework what we already have

Say we create a  new class called *Station*. It only needs a subset of what a full blown settlement would need to function.

**Comment by bevans2000** [comment]
Do we have an issue to cover this change already?

**Pull request merged**
