### PR TITLE
Merge 3.6.2 bugfix onto Master

### PR DESCRIPTION
**Pull request by mokun**
08.27.2023

- change: update change log

### CODE REVIEW

**Comment by mokun** [comment]
@bevans2000 

I've just created a 3.6.X branch. 

Trying to merge the minor changes from 3.6.X back to Master.

**Comment by mokun** [comment]
We could keep this 3.6.X branch open for a day or two for squashing a few more bug fixes if we want to.

**Comment by bevans2000** [comment]
Are you building the 3.6.2 release from this branch?

**Comment by mokun** [comment]
> Are you building the 3.6.2 release from this branch?

Yes.

**Comment by mokun** [comment]
Guess I'm still using the old fashion git ways.

I don't see any git flow options in Eclipse's egit yet.

I'll need to install git command line to use git flow.

**Pull request merged**
