### PR TITLE
Simplify large method and break it into smaller ones

### PR DESCRIPTION
**Pull request by muybien3433**
Simplifying the method can assist with debugging issue #1365

### CODE REVIEW

**Comment by bevans2000** [comment]
@mokun looks good to me.
I'm going to change the trigger on the SonarQube workflow to only fire when we push to a protected branch.

**Comment by mokun** [comment]
```
Error:  Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:4.0.0.4121:sonar (default-cli) on project mars-sim: The 'organization' parameter is missing -> [Help 1]
```

Why is it failed now ?

**Comment by bevans2000** [comment]
It's to do with GitHub security of secrets

**Comment by mokun** [comment]
So do we wait for your to fix that first or simply merge this PR now ?

**Comment by mokun** [comment]
Just a small change. I'll merge or now.

**Pull request merged**
