### PR TITLE
Update Meta mission

### PR DESCRIPTION
**Pull request by bevans2000**
This PR updates the MetaMission interface to remove the static references. It's generally not  good idea to have static references to mangers inside an interface.
The functionality has been relocated to the AbstractMetaMission with the addition of some consolidation of duplicated logic.
Also it has been converted to the immutable MarsTime class.

Part of #650

### CODE REVIEW

**Comment by mokun** [comment]
> generally not good idea to have static references to mangers inside an
interface.
Point taken !

Btw, I've found out Regolith mission doesn't work. Can you take a look at
CollectRegolithMeta.java
<https://github.com/mars-sim/mars-sim/pull/948/files#diff-1fbcc0e5b252029280b2c6d9680e0d36f10d68c8b5cb0e92c21195ff2e9b53af>
since
it fails to scoop up any regoliths at all.

**Comment by bevans2000** [comment]
Does the regolith mission start but get aborted because it can not find a site or does it never get started?

**Comment by mokun** [comment]
> Does the regolith mission start but get aborted 

Yes they can start. 

They never abort.

> because it can not find a site or does it never get started?

They did find all the sites.

However, they never retrieve any regolith and they pack up and go home.

**Comment by bevans2000** [comment]
Ok. That gives me a start on where to look

**Comment by bevans2000** [comment]
I can't find anything obviously wrong; the missions are failing because there is a lack of members that can be recruited.
However I have noticed that there is a massive imbalance between the Exploration & Regolith/Ice missions; the later have a very small probability, less than 1 but the Exploration has probability over 20. This means there is a lack of resource collection missions being started. 
I have found out why this is happening.

**Comment by bevans2000** [comment]
It's because the GoodValue for mineral is returning a high value which is giving the Exploration mission a high probability. I've adjusted the values but obviously this is very sensitive to changes to the Goods calculates.

**Pull request merged**
