### PR TITLE
Remove pulseUI from ClockListener

### PR DESCRIPTION
**Pull request by bevans2000**
This PR addresses some performance issues with the pulsing and simplification of the code base.

First change is the pulseUI method is removed from the ```ClockListener``` interface. Logic is now moved to the existing ```clockPulse``` method. For UI listeners the listeners now have the ability to specify the minimum duration between the delivery of pulses which allows these listeners to work at a slower pace to the main clock. Additionally different UIs can have a different pace, e.g. the TimeTool has a high pace.

Second change is to move the Simulation saving logic out of the ```MasterClock`` and have it solely resides within the Simulation class. The clock should just focus on modelling time and notifying listener to changes in time. The autosaving is now archived by having a dedicated ClockListener that has a duration equal to the auto save period.; hence it fires once per X minutes. The saving is now performed at the end of the Simulation.clockPulse method if there is a save pending

As an aside I did get a NPE from deep inside the Swing UI components but it was not possible to track it's origin because it was triggered via invokeLater in Swing. I think it has nothing to do with these changes. I suspect a window has been changed by a pulse but there was a background refresh queue in the AWTThread.
#527

### CODE REVIEW

**Comment by mokun** [comment]
By design, if the time ratio we want is way too high for the machine to handle, it would reset the time ratio back to 1x.

This happens more often now since the commit.

At 1024x, it starts to happen sometimes

**Comment by bevans2000** [comment]
I feel the root cause us probably more pulses running but I haven't tried any high ratios yet. I might try after Christmas. Wide pulses are certainly a problem.

**Comment by mokun** [comment]
> Wide pulses are certainly a problem.

The sudden increase of the width of the pulses is one problem.

But if we allow the gradual increase of the width of the pulses, then it's not as bad. 

So, if we can *compute* how bad the system stability has become, we can set a limit to how high the time ratio is allowed for each particular machine.   Can we ?

**Comment by bevans2000** [comment]
Yes so the calculations adapt to the actual system being used. It does that to some extent now by using the accuracy setting but that was when the simulation was a lot slower. We have optimised a lot and the approach needs revisiting (& simplifying)

**Pull request merged**
