### PR TITLE
Created a Building tab to the MonitorWindow

### PR DESCRIPTION
**Pull request by bevans2000**
This requests adds a new tab holding Buildings to the MonitorWindow. Th new tab reacts to the Settlement filter.

Selected rows will be displayed in the rebuilt BuildingWindow. This window has a tab per BuildingFunction. These tabs are seeded from the panels in the Settlement Building tab. These panels have been reworked to provide a more consistent approach.
The Building tab has been removed from the Settlement unit window.

#524

### CODE REVIEW

**Comment by mokun** [comment]
@bevans2000 

Can you resolve that ? 

I happened to add the ability in PopUpUnitMenu to view construction sites.

It seems like just the conflict with import statement

**Comment by mokun** [comment]
not just import statements.

A few other places regarding the recognition of construction sites

**Comment by mokun** [comment]
still having conflicts...

**Comment by bevans2000** [comment]
Sure. There were no conflicts when I created it so it must  the the recent commits. I will merge the master and do it that way.

**Comment by bevans2000** [comment]
I've merged it but the "quickStart" option is generating NPE and no UI starts. I will have a look but it seems the UI is constructed out of sequence now. I'll fix it.

**Pull request merged**
