### PR TITLE
Update JFreeChart to 1.5.3

### PR DESCRIPTION
**Pull request by larsnaesbye**
1.5.2 fixes bugs
1.5.3 add a plot type for Sankey diagrams

### CODE REVIEW

**Comment by mokun** [comment]
> Sankey diagrams

Never heard of the term "Sankey diagram" until you mentioned it. I just looked at https://en.wikipedia.org/wiki/Sankey_diagram and it certainly looks cool for illustration.

Where do you see in mars-sim we can give it a shot ?

**Comment by larsnaesbye** [comment]
It's apparently often used for energy flows, and maybe there is no obvious place where we could use one right now. I just thought it was an interesting add.

**Comment by larsnaesbye** [comment]
Also of interest is that they've now deprecated the PieChart3D because they think we should their other chart library https://github.com/jfree/orson-charts instead

**Comment by mokun** [comment]
> Also of interest is that they've now deprecated the PieChart3D because they think we should their other chart library https://github.com/jfree/orson-charts instead

Okay. 

Guess they just made orson-charts compatible with Swing.

We can try converting our codes to using orson charts.

**Comment by mokun** [comment]
I just checked out this [page](https://github.com/jfree/jfreesvg).

This [Sankey diagram](https://raw.githubusercontent.com/jfree/jfreesvg/master/src/main/javadoc/doc-files/FlowPlotDemo2.svg) looks really nice.

**Comment by larsnaesbye** [comment]
> Guess they just made orson-charts compatible with Swing.
> 
> We can try converting our codes to using orson charts.

We could indeed. But maybe it's not high priority....

**Pull request merged**
