### PR TITLE
Merge from 3.6.x

### PR DESCRIPTION
**Pull request by mokun**
1. Rename ConnectWithEarth to ConnectOnline
2. Retune probability for ConnectOnline and ListenToMusic
3. Avoid fast switch from crop to crop in TendGreenhouse
4. Avoid cancelling EVA tasks
5. Reduce codesmells

### CODE REVIEW

**Comment by bevans2000** [comment]
How much more bugfixes do you have for 3.6.2? A lot of these changes are looking like code improvements and not fixes?

**Comment by mokun** [comment]
> A lot of these changes are looking like code improvements and not fixes?

**Comment by mokun** [comment]
> A lot of these changes are looking like code improvements and not fixes?

It's hard to throw in only bugfixes when it can use some improvement right away. Will do my best to keep it clean :D

**Comment by bevans2000** [comment]
> > A lot of these changes are looking like code improvements and not fixes?
> 
> It's hard to throw in only bugfixes when it can use some improvement right away. Will do my best to keep it clean :D

Just be careful you might encounter conflicts in your merge if we start to make changes on master for 3.7.0

**Pull request merged**
