### PR TITLE
Remove embedded timestamps from changelog.gz and mars-sim.1.gz.

### PR DESCRIPTION
**Pull request by lamby**
gzip files can contain an embedded timestamp which can be omitted by
passing "-n". This prevents spurious Debian lintian(1) warnings which are
intended to aid development of reproducible packages.

(These are actually false positives for mars-sim as these files are
hardcoded and thus cannot vary between builds.)

Changes made via:

  $ gzip -9n < ./mars-sim-main/src/deb/changelog > ./mars-sim-main/src/deb/changelog.gz
  $ gzip -9n < ./mars-sim-main/src/deb/man/mars-sim.1 > ./mars-sim-main/src/deb/man/mars-sim.1.gz

Signed-off-by: Chris Lamb <chris@chris-lamb.co.uk>

### CODE REVIEW

**Comment by lamby** [comment]
Related to #2

**Comment by mokun** [comment]
sure! I'll use my fedora to compress both files with the -9n switch and upload them to svn.

**Comment by larsnaesbye** [comment]
We'd need to merge it into the SVN repo I guess. That's the pain of not having the newest code here.

**Comment by lamby** [comment]
Thanks :)

**Pull request closed without merging**
