### PR TITLE
Update the logic behind applying time

### PR DESCRIPTION
**Pull request by bevans2000**
Goal is to refactor the application of simulation time to reduce the need for static references is MarsClock & EarthClock #284

The concept to define a pulse in the simulation as an instance of a `ClockPulse`. Any class that reacts to the passing of time implements a `Temporal` interface. The 'ClockPulse' contains the various clock objects as they stand at that time plus a flag to signify if the pulse has passed into a new day 'isNewSol'. 

Also 'Unit' class can check if the current pulse via `isValid`. This checks that the same pulse is not applied multiple times. This has highlighted a problem in the `UnitManager` and the execution of the `SettlementTask`. Previously these UnitManager did not block and wait for all tasks to complete before advancing; this created the issues where multiple SettlementTask would get queued up in the executor meaning Units were updated multiple times. This has been changed so that for a single pulse all SettlementTask complete as a single phase.

### CODE REVIEW

**Comment by mokun** [comment]
@bevans2000 ,

I just clicked on the "Ready for review" button above. Guess we have to do that every time before we can do a merge, right ?

**Comment by mokun** [comment]
@bevans2000 ,

So now we are presented with 3 choices :
1. Squash and merge
2. Create a merge commit
3. Rebase and merge

Which one is good is the best in our case ?

**Comment by bevans2000** [comment]
I created the PullRequest as draft because it was Work In Progress. I have been rebasing so there should be no merge conflict. In fact the merge should be Fast Forward. I would like to spend another night working on it to complete the initial bulk changes.
In terms of the merge, doing a merge commit should work.

**Comment by bevans2000** [comment]
I have another batch if changes I am working on. These will fix done NPE due to the code not being thread safe. Also a DataLogger concept to consolidate all the various history list throughout the code.

**Comment by mokun** [comment]
@bevans2000 

If you've made some changes, let's do a pull and I'll do a merge to incorporate it. No worry about not finishing everything and purging all the NPE.

**Comment by bevans2000** [comment]
@mokun 
Yes I should have some time tomorrow or Monday. I've been working on the Weather system code. I'll rebase before creating a pull.

**Comment by mokun** [comment]
>  the Weather system code. I'll rebase before creating a pull.

Sure !

When it comes to weather, I imagine we can code in such a way that settlers can take on Meteorology Mission to go to a site to set up weather stations in certain zones for research and for enhancing the weather forecast/predictions of a settlement.

For now, the class related to Meteorology Mission is being disabled since we haven't discussed what to model yet and how it's connected to the goal of a settlement.

**Comment by mokun** [comment]
@bevans2000 ,

This [thread](https://github.com/mars-sim/mars-sim/issues/144) initially discussed about modeling science of the weather data or meteorology. 

If we have new idea and specifically how to implement things, we may as well start a new thread to focus just this topic if you like.

**Comment by bevans2000** [comment]
Sure i can see what the other thread us talking about. I'm focusing on making the code thread safe, optimising and removing "smells" which generally will improve the readability of the code. https://sonarcloud.io/project/issues?id=com.github%3Amars-sim&resolved=false&types=CODE_SMELL

**Pull request merged**
