### PR TITLE
Debug execution time anomaly

### PR DESCRIPTION
**Pull request by mokun**
1.3.2024

- change: benchmark params in calculateSleepTime() in MasterClock

Relates to https://github.com/mars-sim/mars-sim/issues/1204

### CODE REVIEW

**Comment by mokun** [comment]
@bevans2000 

```
01-Adir-01:182.602 (Info) EVAOperation : [25.9400 N 76.3700 E] Gherman Avdeyev - EVA Digging Local Regolith aborted: End of Work Shift.
01-Adir-01:182.602 (Config) MasterClock : execution time = 3586 ms
...
01-Adir-01:187.109 (Info) EVAOperation : [25.9400 N 76.3700 E] Diana Novikov - EVA Digging Local Regolith aborted: End of Work Shift.
01-Adir-01:187.109 (Config) MasterClock : execution time = 1883 ms
...
01-Adir-01:188.923 (Info) EVAOperation : [25.9400 N 76.3700 E] Vladimir Ivanov - EVA Digging Local Regolith aborted: End of Work Shift.
01-Adir-01:188.923 (Info) LifeSupport : [Heritage] Overcrowding at Fish Farm 1.
01-Adir-01:188.923 (Config) MasterClock : execution time = 2652 ms
...
01-Adir-01:279.617 (Info) EVAOperation : [25.9400 N 76.3700 E] Nikita Atkov - EVA Digging Local Regolith aborted: End of Work Shift.
01-Adir-01:279.617 (Config) MasterClock : execution time = 2853 ms
...
01-Adir-01:299.075 (Info) EVAOperation : [25.9400 N 76.3700 E] Viktor Alexeev - EVA Digging Local Regolith aborted: End of Work Shift.
01-Adir-01:299.075 (Config) MasterClock : execution time = 3408 ms
01-Adir-01:299.075 (Warning) MasterClock : [System] MasterClock : executionTime: 3408  optMilliSolPerPulse: 0.437  ave pulse: 0.07623607262248278
...
01-Adir-01:299.075 (Info) EVAOperation : [25.9400 N 76.3700 E] Viktor Alexeev - EVA Digging Local Regolith aborted: End of Work Shift.
01-Adir-01:299.075 (Config) MasterClock : execution time = 3408 ms
01-Adir-01:299.075 (Warning) MasterClock : [System] MasterClock : executionTime: 3408  optMilliSolPerPulse: 0.437  ave pulse: 0.07623607262248278
...
01-Adir-01:355.242 (Info) EVAOperation : [35.2300 N 163.9500 E] Patrick Lopez - EVA Digging Local Regolith aborted: End of Work Shift.
01-Adir-01:355.242 (Config) MasterClock : execution time = 2586 ms
...
01-Adir-01:359.289 (Info) EVAOperation : [35.2300 N 163.9500 E] Wayne Ward - EVA Digging Local Ice aborted: End of Work Shift.
01-Adir-01:359.289 (Config) MasterClock : execution time = 3116 ms





```

**Comment by mokun** [comment]
@bevans2000 

Why and what's behind this *End of Work Shift* notification in `EVAOperation` that would affect the execution time so much ?

**Comment by mokun** [comment]
Rankings:
1. "EVA Digging Local Regolith aborted: End of Work Shift": 3000+ ms
2. WalkOutside's doAreasCollide() is the major culprit: 25 to 65 ms
3. "Overall average # of improvement made on all mineral...": 182 ms
4. "A transport item launched": 84 ms
5. "Reviewing XXX's water ration level": 78 ms

**Comment by bevans2000** [comment]
> Rankings:
> 
> 1. "EVA Digging Local Regolith aborted: End of Work Shift": 3000+ ms
> 2. "Overall average # of improvement made on all mineral...": 182 ms
> 3. WalkOutside's doAreasCollide() is the major culprit: 25 to 65 ms
> 4. "A transport item launched": 84 ms
> 5. "Reviewing XXX's water ration level": 78 ms

Interesting on item 1. My guess is the problem lies in sending them back inside. Without it Persons just keep digging. How did you identify item 1?

**Comment by bevans2000** [comment]
Should the extra investigation code be removed before committing this to the master branch? The master branch should get kept in good status.

**Comment by mokun** [comment]
> Should the extra investigation code be removed before committing this to the master branch? 

Sure ! We don't need to merge at this point. 

Will leave this pull request open for the time being just for debugging purposes. 

Will merge from 3.7.x branch only after adjustment is done to alleviate the spike.

**Comment by mokun** [comment]
>  My guess is the problem lies in sending them back inside. 

Yes I thought so. 

If that's the case, sending a person back may need more CPU power to do pathfinding than going out...

> Without it Persons just keep digging. 

Yay. I wonder what the deal is with calling abort() that uses so much CPU resources. I'll dig deeper.

> How did you identify item 1?

The stacktrace shows it at the same frame that the abort("End of Work Shift") is called in EVAOperation when digging local... For instance, 
```
01-Adir-01:355.242 (Info) EVAOperation : [35.2300 N 163.9500 E] Patrick Lopez - EVA Digging Local Regolith aborted: End of Work Shift.
01-Adir-01:355.242 (Config) MasterClock : execution time = 2586 ms
...
01-Adir-01:359.289 (Info) EVAOperation : [35.2300 N 163.9500 E] Wayne Ward - EVA Digging Local Ice aborted: End of Work Shift.
01-Adir-01:359.289 (Config) MasterClock : execution time = 3116 ms

``` 

I'll try to comment out that shift duty check to see where the rabbit hole goes next.

**Comment by mokun** [comment]
All eyes are on this method `determineObstacleAvoidancePath()` that's within WalkOutside's determineWalkingPath() : 

```java
		else {
			// DEBUG: Calculate the real time elapsed [in milliseconds]
			long tnow = System.currentTimeMillis();
			
			// Determine path around obstacles using A* path planning algorithm.
			List<LocalPosition> obstacleAvoidancePath = determineObstacleAvoidancePath();

			// DEBUG: Calculate the real time elapsed [in milliseconds]
			tLast = System.currentTimeMillis();
			long elapsedMS = tLast - tnow;
			if (elapsedMS > 1000)
				logger.severe(worker, "elapsedMS: " + elapsedMS);
```

I'll try to simplify determineObstacleAvoidancePath(), if possible.

**Pull request merged**
