### PR TITLE
Clear message.properties and sort in alphabetical order #1071

### PR DESCRIPTION
**Pull request by muybien3433**
I cleaned up message.properties and removed unused properties.  I relied on the IDE to identify unused entries, as manually check them would have been too time-consuming.

### CODE REVIEW

**Comment by bevans2000** [comment]
@muybien3433 Sorry, didn't see this. Please mark it for review if you want us to look at it

**Comment by mokun** [comment]
The options inside the menu button no longer have the correct labels : 

image

**Comment by mokun** [comment]
The Preference tab of a Settlement have missing labels : 

image

**Comment by mokun** [comment]
The Air tab of a settlement also have a few missing labels on each metric unit :  

image

**Pull request merged**
