### PR TITLE
Old: Remove dependency on Mission for Loading/Unloading a Vehicle

### PR DESCRIPTION
**Pull request by bevans2000**
This PR removes the dependency on Mission for Loading/Unloading a Vehicle. These operations are now triggered by using new dedicated StatusTypes values. 
In addition the Loading is now instigated by using a ```SuppliesManfiest``` instead of creating a LoadingController. The latter is now a private class to the Vehicle to manage the loading. Requestors of a load have to only specific the supplies to be loaded by a SuppliesManifest.

To support this the definition of Parked vehicles at a settlement has been changed; it now incudes Vehicles visiting from other Settlements.

### CODE REVIEW

**Comment by mokun** [comment]
It has conflicts after some recent commits. 

I won't touch those class now until you merge this PR.

**Comment by bevans2000** [comment]
It's a draft PR not ready yet. Anyway this is a 3.9 change, we need to close down 3.8 and not make any big changes now

**Comment by mokun** [comment]
Does this PR resolve the unloading/loading thread issues of a trading/delivery mission at a destination settlement ?

**Comment by bevans2000** [comment]
It partially resolved it. Certainly simplifies the whole loading and unloading scenarios as it now becomes a function of the Vehicle and not the Mission.
I have to complete a complex merge but should have time to finish it at weekend and get it ready for review

**Comment by bevans2000** [comment]
@mokun I am going to have to abort this branch. You made such big structural changes towards the end of 3.8 when  thought we were just stabling the release that it's proving impossible to merge with any confidence. I will have to redo the change I did to improve the loading & unloading against which is a pain in the arse because I spent quite  but of time on it.

**Comment by mokun** [comment]
Sorry about the last minute changes on the package names. I wasn't thinking about how it will impact your PR and should have.

**Comment by mokun** [comment]
Does the merge on your local machine work ? 

If it does, it could potentially work on the master branch and you don't have to redo it.

**Comment by bevans2000** [comment]
Don't worry. The merge is too messy.

**Comment by mokun** [comment]
It sounds strange it would affect these unrelated files : 

```
Conflicting files
CHANGELOG.md
mars-sim-console/src/main/java/com/mars_sim/console/chat/simcommand/CommandHelper.java
mars-sim-core/src/main/java/com/mars_sim/core/environment/MineralMap.java
mars-sim-core/src/main/java/com/mars_sim/core/environment/RandomMineralMap.java
mars-sim-core/src/main/java/com/mars_sim/core/environment/TerrainElevation.java
mars-sim-core/src/main/java/com/mars_sim/core/map/IntegerMapData.java
mars-sim-core/src/main/java/com/mars_sim/core/map/Map.java
mars-sim-core/src/main/java/com/mars_sim/core/map/MapData.java
mars-sim-core/src/main/java/com/mars_sim/core/map/MapDataFactory.java
mars-sim-core/src/main/java/com/mars_sim/core/map/MapDataUtil.java
mars-sim-core/src/main/java/com/mars_sim/core/map/location/Coordinates.java
mars-sim-core/src/main/java/com/mars_sim/core/map/megdr/MEGDRMapDirect.java
mars-sim-core/src/main/java/com/mars_sim/core/map/megdr/MEGDRMapMemory.java
mars-sim-core/src/main/java/com/mars_sim/core/map/megdr/MEGDRMapReader.java
...
```

**Comment by bevans2000** [comment]
Aborted

**Comment by bevans2000** [comment]
Rejected as too complex merge. Superseded by a new PR

**Pull request closed without merging**
