### PR TITLE
Create a Group Activity concept for meetings

### LINKED ISSUE #1209: Rework the MetaTask of Observing the Night Sky
**Is your feature request related to a problem? Please describe.**
- Currently, `ObserveAstronomicalObjectsMeta` implements `SettlementTask`.
- It does not extends `FactoryMetaTask`.
- A person cannot initiate this task by oneself. 

**Describe the rationale**
- Observing the night sky should be a fun activity for anyone 
- It should not be limited to whether he's writing a scientific paper on this topic or whether he's an astronomer or has a science role, etc.

**Describe the goal(s) you have in mind**
- Make it a group activity for everyone to join in.
- Someone may take the lead role to operate the telescope. Others may simply chime in the sky show.
- Allow it to be selectable in Command Dashboard's Logistic Tab's Task Order combo box.
  -- Allow all other `SettlementTask` to be selectable in Command Dashboard

**Screenshots**
- Ryan is an astronomer
image
- The Command Dashboard's Logistic tab's Task Order Combobox does not have any `SettlementTask` to choose from
image

**Specifications**
- 3.7.0 build 9207

**Additional context**
- Q: Should we have two task, one for professional astronomers doing research using the telescope, the other for amateurs having fun using the telescope's non-research hours ?

### PR DESCRIPTION
**Pull request by bevans2000**
This PR adds the concept of a Group Activity that can represent meetings. There are a number of parts involved:

- GroupActivityInfo is a record that defines the properties of an activity, duration, repeating frequency, meeting place
- GroupActivity is a scheduled activity in a Settlement using a info definition. It uses the existing Scheduled Event logic to advance
- GroupActivityMetaTask converts any active Activities into a SettlementTask that can be assigned
- GtroupActivityTask is assigned to a Person when they participate in an activity

To underpin this the constructor logic of ```Building``` has been corrected and simplified.
There has been numerous UnitTests added/modified.

It also adds configuration for the following default activities; other can be added via settlement.xml:

- Evening Sky Watching party
- Annual Birthday parties
- Announcement meeting when a new Council member is elected
- Welcome party for new arrivals
- Regular team meetings

When a group activity has a Person instigator the Opinion of that person influences the scoring for participants.

A further phase is needed to get participation to improve a Persons stats, e.g. skills.

close #1209 
part #971

### CODE REVIEW

**Comment by mokun** [comment]
How you break down the implementation of the concept of `Group Activity` into at least 4 separate class objects is a very good idea and workable way-forward plan.

**Comment by bevans2000** [comment]
> The way you break down the implementation of the concept of `Group Activity` into at least 4 separate class objects is very nice.
> 
> It's a manageable and workable way-forward plan.

Going full on with Unit Test as well, hence the reason why I reworked to Mock buildings.

**Comment by mokun** [comment]
Merging yet ?

**Comment by bevans2000** [comment]
> Merging yet ?

I've got one cleanup activity on the UnitTest to do and then I will be done for this part. Plus add a Activity for #1209

**Comment by mokun** [comment]
Oh great 🎉❤️

**Comment by bevans2000** [comment]
> Oh great 🎉❤️

It will be ready soon for merging. One of the UnitTests is working locally but failing on GitHub. I think it relates to the randomness of initial Relation Options.

**Comment by bevans2000** [comment]
@mokun We are good to go. I really like this feature.
Phase 2 is how Persons can benefit from attending a Group Activity

**Comment by bevans2000** [comment]
@mokun Just noticed that I haven't added a panel to the Settlement unit wil I'd showing meetings. I'll do that later.
Best thing is to run the future console command and it will show all the scheduled meetings.
Add in any other you can think of I  the Settlement.xml, I think it's quite straight forward. The selection of the Activity Schedule is based on population size.
Enjoy.

**Comment by mokun** [comment]
Now when I started a brand new default scenario session, it throws the following NPE: 

```
01-Adir-01:000.000 (Severe) MarsProject : Problem starting Cannot invoke "com.mars_sim.core.structure.GroupActivitySchedule.specials()" because "schedule" is null
java.lang.NullPointerException: Cannot invoke "com.mars_sim.core.structure.GroupActivitySchedule.specials()" because "schedule" is null
	at com.mars_sim.core.activities.GroupActivity.createPersonActivity(GroupActivity.java:245)
	at com.mars_sim.core.person.Person.calculateBirthDate(Person.java:526)
	at com.mars_sim.core.person.Person.<init>(Person.java:257)
	at com.mars_sim.core.person.PersonBuilder.build(PersonBuilder.java:294)
	at com.mars_sim.core.structure.SettlementBuilder.createPeople(SettlementBuilder.java:434)
	at com.mars_sim.core.structure.SettlementBuilder.createFullSettlement(SettlementBuilder.java:137)
	at com.mars_sim.core.structure.SettlementBuilder.createInitialSettlements(SettlementBuilder.java:97)
	at com.mars_sim.core.SimulationBuilder.start(SimulationBuilder.java:320)
	at com.mars_sim.ui.main.MarsProject.parseArgs(MarsProject.java:203)
	at com.mars_sim.ui.main.MarsProject.main(MarsProject.java:463)
```

The line ```var activityInfo = schedule.specials().get(type);``` won't work.

**Comment by bevans2000** [comment]
@mokun Sorry about that. It's a problem with small Settlement because they don't have a Schedule defined currently.
I have just pushed a fix.
The Schedules need refining in the Settlements.xml.

**Pull request merged**
