### PR TITLE
DataLogger application to Person and Weather

### PR DESCRIPTION
**Pull request by bevans2000**
#284 Applied  the DataLogger pattern to more classes to remove the dependency on MarsClock.
The DataLogger also reduces duplicate/similar code into a common place.
The Weather class has been reworked to make it ThreadSafe.

### CODE REVIEW

**Comment by mokun** [comment]
@bevans2000 

I've got the following after I increase the time ratio to 1024x 👍 


```
00-Adir-01:234.846 (Info) RepairMalfunction : [Zvezda] Dániel Sokolov was appointed as the chief repairer handling the Emergency Repair for 'Water Contamination' on Lander Hab 1
00-Adir-01:234.846 (Info) RepairMalfunction : [Zvezda] Paul Berezovoy was appointed as the deputy repairer handling the Emergency Repair for 'Water Contamination' on Lander Hab 1
00-Adir-01:235.154 (Info) Malfunction : Water Contamination - incident #1 - Emergency repair work initiated by Dániel Sokolov.
00-Adir-01:262.659 (Warning) UpTimer : Time limit exceeded between the last and this call, total # of pulses : 1008
00-Adir-01:263.434 (Warning) MasterClock$ClockThreadTask : excess: 631 ms. currentTBU : 106 ms. executionTime : 738 ms. Recovering from a lost frame (Skips # 1).
00-Adir-01:264.498 (Warning) MasterClock$ClockThreadTask : excess: 525 ms. currentTBU : 106 ms. executionTime : 738 ms. Recovering from a lost frame (Skips # 2).
00-Adir-01:264.543 (Warning) MasterClock$ClockThreadTask : excess: 419 ms. currentTBU : 106 ms. executionTime : 738 ms. Recovering from a lost frame (Skips # 3).
00-Adir-01:264.591 (Warning) MasterClock$ClockThreadTask : excess: 312 ms. currentTBU : 106 ms. executionTime : 738 ms. Recovering from a lost frame (Skips # 4).
00-Adir-01:264.628 (Warning) MasterClock$ClockThreadTask : excess: 206 ms. currentTBU : 106 ms. executionTime : 738 ms. Recovering from a lost frame (Skips # 5).
00-Adir-01:266.640 (Warning) UpTimer : Time limit exceeded between the last and this call, total # of pulses : 15
00-Adir-01:266.640 (Warning) MasterClock$ClockThreadTask : excess: 930 ms. currentTBU : 106 ms. executionTime : 1036 ms. Recovering from a lost frame (Skips # 1).
00-Adir-01:266.792 (Warning) MasterClock$ClockThreadTask : excess: 823 ms. currentTBU : 106 ms. executionTime : 1036 ms. Recovering from a lost frame (Skips # 2).
00-Adir-01:266.833 (Warning) MasterClock$ClockThreadTask : excess: 717 ms. currentTBU : 106 ms. executionTime : 1036 ms. Recovering from a lost frame (Skips # 3).
00-Adir-01:266.876 (Warning) MasterClock$ClockThreadTask : excess: 611 ms. currentTBU : 106 ms. executionTime : 1036 ms. Recovering from a lost frame (Skips # 4).
00-Adir-01:266.914 (Warning) MasterClock$ClockThreadTask : excess: 504 ms. currentTBU : 106 ms. executionTime : 1036 ms. Recovering from a lost frame (Skips # 5).
00-Adir-01:266.952 (Warning) MasterClock$ClockThreadTask : excess: 398 ms. currentTBU : 106 ms. executionTime : 1036 ms. Recovering from a lost frame (Skips # 6).
00-Adir-01:266.994 (Warning) MasterClock$ClockThreadTask : excess: 292 ms. currentTBU : 106 ms. executionTime : 1036 ms. Recovering from a lost frame (Skips # 7).
00-Adir-01:267.033 (Warning) MasterClock$ClockThreadTask : excess: 185 ms. currentTBU : 106 ms. executionTime : 1036 ms. Recovering from a lost frame (Skips # 8).
00-Adir-01:268.045 (Warning) MasterClock$ClockThreadTask : excess: 546 ms. currentTBU : 106 ms. executionTime : 652 ms. Recovering from a lost frame (Skips # 1).
00-Adir-01:268.985 (Warning) MasterClock$ClockThreadTask : excess: 439 ms. currentTBU : 106 ms. executionTime : 652 ms. Recovering from a lost frame (Skips # 2).
00-Adir-01:269.035 (Warning) MasterClock$ClockThreadTask : excess: 333 ms. currentTBU : 106 ms. executionTime : 652 ms. Recovering from a lost frame (Skips # 3).
00-Adir-01:269.078 (Warning) MasterClock$ClockThreadTask : excess: 227 ms. currentTBU : 106 ms. executionTime : 652 ms. Recovering from a lost frame (Skips # 4).
00-Adir-01:269.117 (Warning) MasterClock$ClockThreadTask : excess: 120 ms. currentTBU : 106 ms. executionTime : 652 ms. Recovering from a lost frame (Skips # 5).
00-Adir-01:269.344 (Warning) MasterClock$ClockThreadTask : excess: 576 ms. currentTBU : 106 ms. executionTime : 682 ms. Recovering from a lost frame (Skips # 1).
00-Adir-01:270.329 (Warning) MasterClock$ClockThreadTask : excess: 469 ms. currentTBU : 106 ms. executionTime : 682 ms. Recovering from a lost frame (Skips # 2).
00-Adir-01:270.373 (Warning) MasterClock$ClockThreadTask : excess: 363 ms. currentTBU : 106 ms. executionTime : 682 ms. Recovering from a lost frame (Skips # 3).
00-Adir-01:270.419 (Warning) MasterClock$ClockThreadTask : excess: 257 ms. currentTBU : 106 ms. executionTime : 682 ms. Recovering from a lost frame (Skips # 4).
00-Adir-01:270.468 (Warning) MasterClock$ClockThreadTask : excess: 150 ms. currentTBU : 106 ms. executionTime : 682 ms. Recovering from a lost frame (Skips # 5).
```

We may need to finetune the run() in `ClockThreadTask`

**Comment by mokun** [comment]
@bevans2000

**Comment by bevans2000** [comment]
I agree the Masterclock and Uptimer classes seem to be over complex. This is now occuring because the ClockListerners are correctly blocking now so they stay in sequence according to the MasterClock. So the listeners take longer to complete. Before the listeners were running asynchronously and of course they complete quicker. There are a few aspects I thought about. 

1. Optimise the core code so it is more efficient and quicker. I feel the high use of CopyOnWriteList will costs some CPU cycles. In theory if the code is thread safe normal faster ArrayLists can be used.
2. There are areas in the logic where the code can be optimised, for example there are a lot of instanceof calls in the base classes suggesting the execution is not optimised for just the subclasses. This probably needs profiling to find the hotspots.
3. The Masterclock is using a lot of absolute time limits and rates to control the time ratio. I don't understand what this trying to do.
4. The UI is updated as part of the MasterClock thread.

**Comment by mokun** [comment]
@bevans2000 
Sure. So let's simplify the code.

Also I was trying to pull some stats on what happen on each frame.

See those labels indicators in the Time Tool.

**Comment by bevans2000** [comment]
I have created #287

**Pull request merged**
