### PR TITLE
Person FatorymetaTask Blueprint

### PR DESCRIPTION
**Pull request by bevans2000**
This pull request covers a number of changes with the single objective of giving a user more understanding to how Tasks are automatically selected for Persons.

This converts a number of the ```MetaTask``` instances to use the common 'assess*' method provided to be commonly re-used. MetaTask following the blueprint implement the ```getTaskJobs``` method.

Within ```PhysicalCondition``` the muscle skeleton array is converted to explicit fields to improve readabilitiy.
 
In addition the Activity tab in the Person & Robot unit window has been redesigned so that it can show the alternative Tasks not chosen. Each one has a score where the tooltip shows the score composition.

Part of #1084

### CODE REVIEW

**Comment by mokun** [comment]
image

I can see how the composite score of 7.707 came to be for Inam Almutairi. 

The base score was adjusted by 5 modifiers.

**Comment by mokun** [comment]
Interesting that Maria was `Writing Study Collaboration Invitation` and it has 8 modifiers.
image

In that Person Window below, I can see the composite score of 146.36.
image

Can we still have the subtask and show it in TabPanelActivity ?

**Comment by mokun** [comment]
Never mind. I can see the subtask(s) now below : 

image

**Comment by bevans2000** [comment]
> Never mind. I can see the subtask(s) now below :

Yes I collapsed the subtasks to make space for the task choice table. I think it works well

**Comment by bevans2000** [comment]
> 
> I can see how the composite score of 7.707 came to be for Inam Almutairi.
> 
> The base score was adjusted by 5 modifiers.

Yes it's really useful. By using a set of common assess methods the modifiers are consistent and applied in the same way. Do you see that modifiers have a 'x'? Some Tasks have a composite base score as well

**Pull request merged**
