### PR TITLE
Delivery a new approach to managing Missions

### LINKED ISSUE #890: Create a new TestDrive Mission
Create a new Mission instance based on the new Mission Project approach. This will cover the basic steps of a Mission:

1. Review
2. Load Vehicle
3. Embark
4. Drive 
5. Disembark

### PR DESCRIPTION
**Pull request by bevans2000**
This PR deliveries a new approach to managing Mission. 

This new approach is demonstrated in a new Mission called ```TestDriveMission```. This mission can only be created via the console _create mission_ command at the moment.
The new mission type is fully integrated into the Monitor & Mission tools and the console commands

The new approach concept represents the Mission as a number of seperate ```MissionStep``` where the new ```Project``` class is used to progress and advance throught the steps.
This provides a very easy to understand and flexible. There are a number of common shared steps:
* ```MissionTravelStep```  - involves driving from one ```NavPoint``` to another.
* ```MissionBoardVehicleStep``` - handles getting members to board a vehicle
* ```MissionLoadVehicleStep``` - handles loading a vehicle, could be the start or in the middle as in a Trade mission.

To accompany the changes there calculation of requires "supplies" has been changed. Each unprocessed step is queries for the suplies it needs. These are captured in a new ```MissionManifest``` class.

Note the current implemented steps do not have the full feature of the old Missions, e.g. no handling of Vehicle malfunctions.

Close #890

### CODE REVIEW

**Comment by mokun** [comment]
Finally the Project Mission delivered !

**Comment by bevans2000** [comment]
Yes took a while but I'm very happy with the outcome. The nature if using a set of steps is really clean

**Comment by mokun** [comment]
Yes I can appreciate that there's no more crazy calling of
determineNewPhase() and performPhase() !

**Comment by bevans2000** [comment]
I want to convert the dig missions next as that will introduce an sharable EVA step. 
Also need to do

- Checking resources during the mission
- Selecting vehicles
- selecting members

**Comment by mokun** [comment]
> dig missions next as that will introduce an sharable EVA step.

I like that. Will there be a division of labor in these types of outside EVA activities ? 

I suppose in terms of building a weather station, there will be many activities involved and person A may be doing X and Y, while person B may be doing Y and Z and person C may be doing X and Z, etc.

That's why if we can implement the idea of the **shared** task first (please see and comment on #919), then it may get really easy to implement capture the spirit of a sharable EVA step.

What would you say ?

**Comment by mokun** [comment]
@bevans2000

Do you want to continue on this thread ?

**Comment by bevans2000** [comment]
This pr is closed now

**Pull request merged**
